import Head from "next/head";
import Link from "next/link";
import ThemeButton from "../components/theme-button";
import styles from "../styles/Home.module.css";
import { useContext, useEffect } from "react";
import { ThemeContext, ThemeUpdateContext } from "../context/themeContext";

export default function Home() {
  const darkTheme = useContext(ThemeContext);
  const toggleTheme = useContext(ThemeUpdateContext);
  const themeStyle = {
    backgroundColor: darkTheme ? "#222222" : "#ffffff",
    color: darkTheme ? "#ffffff" : "#222222",
  };

  useEffect(() => {
    if (
      window.matchMedia &&
      window.matchMedia("(prefers-color-scheme: dark)").matches
    ) {
      toggleTheme(true);
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={themeStyle} className={styles.main}>
        <Link href="/about">
          <a>About</a>
        </Link>
        <ThemeButton></ThemeButton>
      </main>
    </div>
  );
}
